"""add_pdf_bytes_to_tailored_resumes

Revision ID: 00eee45844e5
Revises: 17fce7598250
Create Date: 2026-03-24 15:55:59.905804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00eee45844e5'
down_revision: Union[str, Sequence[str], None] = '17fce7598250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TABLE tailored_resumes ADD COLUMN IF NOT EXISTS pdf_bytes BYTEA")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_resumes', 'pdf_bytes')
    # ### end Alembic commands ###
