"""add_email_to_tailored_resumes

Revision ID: 17fce7598250
Revises: c06de09b054a
Create Date: 2026-03-24 15:47:44.496206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fce7598250'
down_revision: Union[str, Sequence[str], None] = 'c06de09b054a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tailored_resumes', sa.Column('email_subject', sa.Text(), nullable=True))
    op.add_column('tailored_resumes', sa.Column('email_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_resumes', 'email_body')
    op.drop_column('tailored_resumes', 'email_subject')
    # ### end Alembic commands ###
