"""cascade_delete_user_fks

Revision ID: 2303d3bbc034
Revises: f1a2b3c4d5e6
Create Date: 2026-03-28 19:59:50.240278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2303d3bbc034'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_results_user_id_fkey'), 'job_results', type_='foreignkey')
    op.drop_constraint(op.f('job_results_run_id_fkey'), 'job_results', type_='foreignkey')
    op.create_foreign_key(None, 'job_results', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_results', 'runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_jobs_raw_ingested_at'), table_name='jobs_raw')
    op.drop_index(op.f('ix_jobs_raw_role_clusters'), table_name='jobs_raw', postgresql_using='gin')
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('runs_user_id_fkey'), 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tailored_resumes_user_id_fkey'), 'tailored_resumes', type_='foreignkey')
    op.create_foreign_key(None, 'tailored_resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tailored_resumes', type_='foreignkey')
    op.create_foreign_key(op.f('tailored_resumes_user_id_fkey'), 'tailored_resumes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(op.f('runs_user_id_fkey'), 'runs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_jobs_raw_role_clusters'), 'jobs_raw', ['role_clusters'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_jobs_raw_ingested_at'), 'jobs_raw', ['ingested_at'], unique=False)
    op.drop_constraint(None, 'job_results', type_='foreignkey')
    op.drop_constraint(None, 'job_results', type_='foreignkey')
    op.create_foreign_key(op.f('job_results_run_id_fkey'), 'job_results', 'runs', ['run_id'], ['id'])
    op.create_foreign_key(op.f('job_results_user_id_fkey'), 'job_results', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
