"""add_worker_lease_columns_to_runs

Revision ID: 4972000b8cc0
Revises: 4c9f1d2e3b4a
Create Date: 2026-04-06 14:48:11.973945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4972000b8cc0'
down_revision: Union[str, Sequence[str], None] = '4c9f1d2e3b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_raw_embedding_hnsw'), table_name='jobs_raw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.alter_column('query_plan_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('query_plan_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('runs', sa.Column('claimed_by', sa.String(length=255), nullable=True))
    op.add_column('runs', sa.Column('claim_token', sa.String(length=64), nullable=True))
    op.add_column('runs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('runs', sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('runs', sa.Column('cancel_requested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('runs', sa.Column('trigger_source', sa.String(length=50), nullable=True))
    op.add_column('runs', sa.Column('executor_type', sa.String(length=50), nullable=True))
    op.create_index('ix_runs_claim', 'runs', ['status', 'mode', 'lease_expires_at', 'started_at'], unique=False)
    # Drop as constraint (not index) — Postgres backed this with a constraint, not a plain index
    op.drop_constraint('uq_scrape_query_cache_key', 'scrape_query_cache', type_='unique')
    op.create_unique_constraint('uq_scrape_query_cache_key', 'scrape_query_cache', ['provider', 'site', 'term_normalized', 'location_normalized', 'country_normalized', 'hours_old'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scrape_query_cache_key', 'scrape_query_cache', type_='unique')
    op.create_index(op.f('uq_scrape_query_cache_key'), 'scrape_query_cache', ['provider', 'site', 'term_normalized', 'location_normalized', 'country_normalized', 'hours_old'], unique=True)
    op.drop_index('ix_runs_claim', table_name='runs')
    op.drop_column('runs', 'executor_type')
    op.drop_column('runs', 'trigger_source')
    op.drop_column('runs', 'cancel_requested')
    op.drop_column('runs', 'attempt_count')
    op.drop_column('runs', 'last_heartbeat_at')
    op.drop_column('runs', 'lease_expires_at')
    op.drop_column('runs', 'claim_token')
    op.drop_column('runs', 'claimed_by')
    op.alter_column('query_plan_cache', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('query_plan_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_jobs_raw_embedding_hnsw'), 'jobs_raw', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    # ### end Alembic commands ###
