"""add_retry_fields_to_generation_queue

Revision ID: 90e3a061d643
Revises: 00eee45844e5
Create Date: 2026-03-24 16:03:40.149592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e3a061d643'
down_revision: Union[str, Sequence[str], None] = '00eee45844e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_queue', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('generation_queue', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_queue', 'next_retry_at')
    op.drop_column('generation_queue', 'retry_count')
    # ### end Alembic commands ###
