"""jobdigest: work_auth, domain, emailed_at on job_results

Revision ID: e1c0a7b113bc
Revises: 6c7d8e9f0a1b
Create Date: 2026-06-27 22:26:37.977781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c0a7b113bc'
down_revision: Union[str, Sequence[str], None] = '6c7d8e9f0a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_results', sa.Column('work_auth_verdict', sa.String(length=50), nullable=True))
    op.add_column('job_results', sa.Column('work_auth_evidence', sa.Text(), nullable=True))
    op.add_column('job_results', sa.Column('domain', sa.String(length=100), nullable=True))
    op.add_column('job_results', sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_jr_user_final_score_job'), table_name='job_results')
    op.drop_constraint(op.f('recruiter_refresh_tasks_user_id_fkey'), 'recruiter_refresh_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'recruiter_refresh_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recruiter_refresh_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('recruiter_refresh_tasks_user_id_fkey'), 'recruiter_refresh_tasks', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_jr_user_final_score_job'), 'job_results', ['user_id', sa.literal_column('final_score DESC'), 'job_id'], unique=False)
    op.drop_column('job_results', 'emailed_at')
    op.drop_column('job_results', 'domain')
    op.drop_column('job_results', 'work_auth_evidence')
    op.drop_column('job_results', 'work_auth_verdict')
    # ### end Alembic commands ###
