"""add_embeddings_table

Revision ID: e6ac31c5faee
Revises: 0c58239561e0
Create Date: 2026-03-22 00:19:22.566425

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ac31c5faee'
down_revision: Union[str, Sequence[str], None] = '0c58239561e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('text_fp', sa.String(length=64), nullable=False),
    sa.Column('cfg_fp', sa.String(length=32), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_fp', 'cfg_fp', name='uq_embedding_text_cfg')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embeddings')
    # ### end Alembic commands ###
