"""Digest rendering + delivery.

Takes scored jobs -> groups by domain -> renders one HTML email -> sends via Gmail.
Email-client-safe: all styles inline, simple table-free layout.
"""
from __future__ import annotations

import smtplib
from email.message import EmailMessage
from email.utils import formatdate

# --- domain classification (cheap, deterministic, from title) ---
DOMAIN_RULES = [
    ("Clock / CDC", ["clock", "cdc", "clocking"]),
    ("Timing / STA", ["timing", "sta", "static timing", "signoff", "sign-off"]),
    ("CPU / GPU RTL", ["cpu", "gpu", "tpu", "npu", "riscv", "risc-v", "microarchitecture"]),
    ("Physical Design", ["physical design", "place", "route", "floorplan", "pnr"]),
    ("RTL / ASIC / SoC", ["rtl", "asic", "soc", "vlsi", "digital design", "logic design"]),
]
BAND_LABEL = {"strong_fit": "Strong", "adjacent_fit": "Adjacent",
              "weak_fit": "Weak", "misleading_fit": "Misleading", "reject": "Reject"}
BAND_COLOR = {"strong_fit": "#1a7f37", "adjacent_fit": "#0969da",
              "weak_fit": "#9a6700", "misleading_fit": "#bc4c00", "reject": "#cf222e"}


def classify_domain(title: str) -> str:
    t = (title or "").lower()
    for name, kws in DOMAIN_RULES:
        if any(k in t for k in kws):
            return name
    return "Other IC Design"


def _reason(report: dict) -> str:
    s = report.get("summary") or report.get("explanation_summary") or ""
    s = s.strip()
    # keep it to the first sentence, capped — minimalist
    first = s.split(". ")[0].strip()
    if first and not first.endswith("."):
        first += "."
    return first[:140]


def render_digest(scored: list, *, profile_label: str, date_str: str) -> tuple[str, str]:
    """scored = list of (band, job, report). Returns (subject, html)."""
    # group strong/adjacent (already filtered upstream) by domain
    groups: dict[str, list] = {}
    for band, job, report in scored:
        groups.setdefault(classify_domain(job.title), []).append((band, job, report))
    # order domains by best-fit count
    ordered = sorted(groups.items(), key=lambda kv: -len(kv[1]))

    total = len(scored)
    subject = f"JobDigest · {total} matches · {date_str}"

    parts = [
        '<div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;'
        'max-width:640px;margin:0 auto;color:#1f2328;line-height:1.4;">',
        f'<p style="color:#656d76;margin:0 0 16px;font-size:13px;">'
        f'{total} matches · {profile_label} · {date_str}</p>',
    ]
    if total == 0:
        parts.append('<p>No new strong matches today. The scraper ran fine — '
                     'just nothing fresh in your lane in the last 24h.</p>')
    for domain, jobs in ordered:
        parts.append(f'<h3 style="margin:24px 0 8px;border-bottom:1px solid #d0d7de;'
                     f'padding-bottom:4px;">{domain} <span style="color:#656d76;'
                     f'font-weight:normal;font-size:13px;">({len(jobs)})</span></h3>')
        for band, job, report in jobs:
            color = BAND_COLOR.get(band, "#656d76")
            label = BAND_LABEL.get(band, band)
            loc = job.location or "—"
            reason = _reason(report)
            parts.append(
                f'<div style="margin:0 0 14px;padding:10px 12px;border:1px solid #d0d7de;'
                f'border-radius:8px;">'
                f'<div style="display:flex;justify-content:space-between;align-items:baseline;">'
                f'<a href="{job.job_url}" style="font-weight:600;font-size:15px;color:#0969da;'
                f'text-decoration:none;">{job.title}</a>'
                f'<span style="background:{color};color:#fff;font-size:11px;padding:2px 8px;'
                f'border-radius:10px;white-space:nowrap;margin-left:8px;">{label}</span></div>'
                f'<div style="color:#656d76;font-size:13px;margin:2px 0 4px;">'
                f'{job.company or "—"} · {loc}</div>'
                + (f'<div style="font-size:13px;color:#1f2328;">{reason}</div>' if reason else '')
                + '</div>'
            )
    parts.append('<p style="color:#8b949e;font-size:12px;margin-top:24px;">'
                 'Generated by your JobDigest pipeline.</p></div>')
    return subject, "\n".join(parts)


def send_email(*, subject: str, html: str, sender: str, app_password: str,
               recipients: list[str]) -> None:
    """Send via Gmail SMTP over SSL. app_password is a 16-char Gmail app password."""
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)
    msg["Date"] = formatdate(localtime=True)
    msg.set_content("This digest is best viewed in an HTML-capable email client.")
    msg.add_alternative(html, subtype="html")

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, app_password)
        server.send_message(msg)